# Generated by Django 3.2.16 on 2022-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221215_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='created_date_to_send',
            field=models.DateTimeField(),
        ),
    ]
