# Generated by Django 3.2.16 on 2022-12-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221214_2118'),
        ('main', '0004_auto_20221215_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mails',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_date_to_send',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_c', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_m', to='main.mails'),
        ),
    ]
