# Generated by Django 3.2.16 on 2022-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221215_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
